---
- hosts: webservers 
  sudo: yes
  tasks:
      - name: Install apache and git.
        pacman: name={{ item }} state=present update_cache=yes
        with_items:
            - apache
            - git
      - name: Make sure nginx is started and configure it to run at boot.
        service: name=httpd state=started enabled=yes


