---
- hosts: webservers 
  sudo: yes
  tasks:
      - name: Install apache.
        pacman: name={{ item }} state=present update_cache=yes
        with_items:
            - apache
      - name: Make sure nginx is started and configure it to run at boot.
        service: name=httpd state=started enabled=yes


