---
- hosts: rp
  sudo: yes
  tasks:
      - name: Install haproxy.
        pacman: name={{ item }} state=present update_cache=yes
        with_items:
            - haproxy



      - name: Configure the haproxy cnf file with hosts
        copy: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
        notify: restart haproxy




      - name: Make sure habproxy is started and configure it to run at boot.
        service: name=haproxy state=started enabled=yes


